# Generated by Django 5.1.7 on 2025-03-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Статус подписки"),
        ),
    ]
