# Generated by Django 5.1.7 on 2025-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id сессии",
                max_length=255,
                null=True,
                verbose_name="id сессии",
            ),
        ),
    ]
