# Generated by Django 5.1.7 on 2025-04-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_owner_lesson_owner"),
        ("users", "0005_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="course_paid",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lesson_paid",
        ),
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
