# Generated by Django 5.1.7 on 2025-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course",
            new_name="courses",
        ),
        migrations.AddField(
            model_name="course",
            name="lessons",
            field=models.ManyToManyField(to="materials.lesson", verbose_name="Уроки"),
        ),
    ]
